# Misc
    bindsym $mod+Shift+w kill
    bindsym $mod+Shift+c reload

    bindsym $mod+b exec "brave --password-store=basic"
    bindsym $mod+s exec "spotify"
    bindsym $mod+e exec "dolphin"

    # Tools
    bindsym $mod+Return exec alacritty
    bindsym $mod+space exec "wofi --show drun"

# Resize
    mode "resize" {
        bindsym $mod+r mode "default"
    }
    bindsym $mod+r mode "resize"


# Exit
    bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'

# Mouse

# Autostart clipboard managers
exec wl-paste -t text --watch clipman store
exec wl-paste -p -t image --watch clipman store

# Screenshots and clipboard
bindsym $mod+Shift+s exec grim -g "$(slurp)" - | wl-copy  # Area screenshots
bindsym $mod+v exec clipman pick -t wofi

