eval "$(zoxide init --cmd cd zsh)"
eval "$(fzf --zsh)"

autoload -U compinit
zmodload zsh/complist
compinit
_comp_options+=(globdots) # Include hidden files.

zstyle ':completion:*' matcher-list 'm:{a-z}={a-zA-Z}'
zstyle ':completion:*' list-colors '{(s.:.)LS_COLORS}'
zstyle ':completion:*' menu no

zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

bindkey '^I' complete-word        # tab
bindkey '^[[Z' forward-word       # shift + tab
bindkey '^[^I' autosuggest-accept # shift + tab

clear-terminal() {
  tput reset
  zle redisplay
}
zle -N clear-terminal
bindkey '^[l' clear-terminal
bindkey -M viins '^[l' clear-terminal

# bindkey '^[[1;5A' history-search-backward
# bindkey '^[[1;5B' history-search-forward

bindkey '^[k' history-search-backward
bindkey '^[j' history-search-forward
bindkey -M viins '^[k' history-search-backward
bindkey -M viins '^[j' history-search-forward

eval "$(starship init zsh)"
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

alias tr="tree --gitignore -L 3 -a";
alias ga="git add . && clear";
alias gs="git status";
alias gc="git commit -m ";
alias gp="git push && clear";

alias -g nano="nvim"

# Declare the ZSH_HIGHLIGHT_STYLES array for syntax highlighting color overrides
typeset -A ZSH_HIGHLIGHT_STYLES

# Map zsh-syntax-highlighting styles to your alacritty hex colors
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#ca1444'                    # red for errors
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#cb6fa1,bold'               # magenta for keywords like 'if', 'for'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#aca1cf'                            # cyan for aliases
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#e8a831'                          # yellow for builtins
ZSH_HIGHLIGHT_STYLES[function]='fg=#90b99f'                         # green for functions
ZSH_HIGHLIGHT_STYLES[command]='fg=#90b99f'                          # green for commands
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#e8a831,underline'             # yellow underlined for precommands
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#c9c7cd'                 # foreground color for separators
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#90b99f'                   # green for hashed commands
ZSH_HIGHLIGHT_STYLES[path]='fg=#aca1cf'                             # cyan for paths
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#aca1cf,underline'            # cyan underlined for path prefixes
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#b9aeda'                         # blue for globbing
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#cb6fa1,bold'           # magenta bold for history expansion
ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=#282828,bg=#e8a831'  # black on yellow for command substitution
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#e8a831'   # yellow for delimiters
ZSH_HIGHLIGHT_STYLES[process-substitution]='fg=#282828,bg=#e8a831'  # black on yellow
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#e8a831'   # yellow for delimiters
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#aca1cf'             # cyan for -options
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#aca1cf'             # cyan for --options
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#282828,bg=#e8a831'  # black on yellow for backticks
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#e8a831'           # yellow for 'strings'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#e8a831'           # yellow for "strings"
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#e8a831'           # yellow for $'strings'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#aca1cf'                         # cyan for RC quotes
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#cb6fa1'    # magenta for $var inside quotes
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#aca1cf'      # cyan for escape sequences
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#aca1cf'      # cyan for escape sequences
ZSH_HIGHLIGHT_STYLES[assign]='fg=#cb6fa1'                           # magenta for assignments
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#e8a831,bold'                 # yellow bold for redirections
ZSH_HIGHLIGHT_STYLES[comment]='fg=#282828,bold'                     # dark gray for comments
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#b9aeda'                         # blue for named file descriptors
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#b9aeda'                       # blue for numeric file descriptors
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#c9c7cd'                             # foreground for other command words
ZSH_HIGHLIGHT_STYLES[default]='fg=#c9c7cd'                          # foreground for everything else
